export {default as Birthday} from './Birthday'
export {default as Identity} from './Identity'
export {default as Email} from './Email'
export {default as ConnectPlatform} from './ConnectPlatform'
export {default as Interest} from './Interest'
export {default as Name} from './Name'
export {default as MusicBreakdown} from './components/MusicBreakdown'